### ISSUE TITLE
Number of tokens in diskstats varies depending on kernel version

### ISSUE THREAD

**Issue by gramound** [xrmx/bootchart#87]
The parsing of the disk stats isn't working for new kernels due to ```is_relevant_line``` expecting 14 tokens. See kernel doc below.

https://github.com/xrmx/bootchart/blob/868a2afab9da34f32c007d773b77253c93104636/pybootchartgui/parsing.py#L458

https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats

**Comment by mmeeks** [comment]
Good catch, want to submit a simple back-compatible pull request =) would be great to have your contribution.
